-- name: CreateFeedFollow :one
WITH INSERTED_FEED_FOLLOW AS (
  INSERT INTO FEED_FOLLOWS (
    ID,
    CREATED_AT,
    UPDATED_AT,
    USER_ID,
    FEED_ID
  ) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
  )
  RETURNING *
)
SELECT IFF.*,
       F.NAME FEED_NAME,
       U.NAME USERNAME
  FROM INSERTED_FEED_FOLLOW IFF
  JOIN FEEDS F ON IFF.FEED_ID = F.ID
  JOIN USERS U ON IFF.USER_ID = U.ID;

-- name: GetFeedFollowsByUser :many
SELECT F.NAME FEED_NAME,
       U.NAME USERNAME
  FROM FEED_FOLLOWS FF
  JOIN FEEDS F ON FF.FEED_ID = F.ID
  JOIN USERS U ON FF.USER_ID = U.ID
 WHERE U.NAME = $1;