-- +goose Up
CREATE TABLE FEEDS (
  ID UUID PRIMARY KEY,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  NAME TEXT NOT NULL,
  URL TEXT UNIQUE NOT NULL,
  USER_ID UUID NOT NULL,
  CONSTRAINT FK_USERS 
  FOREIGN KEY (USER_ID) 
  REFERENCES USERS(ID) 
  ON DELETE CASCADE
);

-- +goose Down
DROP TABLE FEEDS;