-- +goose Up
CREATE TABLE FEED_FOLLOWS(
  ID UUID PRIMARY KEY,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  USER_ID UUID NOT NULL,
  FEED_ID UUID NOT NULL,
  CONSTRAINT UK_USER_FEED UNIQUE (USER_ID, FEED_ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_FEED FOREIGN KEY (FEED_ID) REFERENCES FEEDS(ID) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE FEED_FOLLOWS;