-- +goose Up
CREATE TABLE POSTS (
  ID UUID PRIMARY KEY,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  TITLE TEXT NOT NULL,
  URL TEXT NOT NULL UNIQUE,
  DESCRIPTION TEXT,
  PUBLISHED_AT TIMESTAMP,
  FEED_ID UUID NOT NULL,
  CONSTRAINT FK_FEED FOREIGN KEY (FEED_ID) REFERENCES FEEDS(ID)
);

-- +goose Down
DROP TABLE POSTS;